# Generated by Django 4.0.5 on 2022-06-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='datatime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
